-- 在vscode插件的基础上设置透明背景

local function nbghl(hl_group)
    vim.api.nvim_set_hl(0, hl_group, { bg = nil })
end


nbghl("Normal")
nbghl("NonText")
nbghl("LineNr")
nbghl("CurosrLineNr")
nbghl("SignColumn")
nbghl("Folded")
nbghl("FoldColumn")
nbghl("DiffAdd")
nbghl("DiffChange")
nbghl("DiffDelete")
nbghl("DiffText")
nbghl("DiffAdded")
nbghl("DiffRemoved")
nbghl("TabLineFill")
nbghl("ModeMsg")
nbghl("MoreMsg")
nbghl("NvimTreeNormal")
nbghl("NvimTreeOpenedFolderName")
nbghl("BufferLineFill")
nbghl("NvimTreeCurosrLine")
nbghl("NvimTreeEndOfBuffer")
nbghl("NeoTreeCursorLine")
nbghl("NeoTreeDimText")
nbghl("NeoTreeFileNameOpened")
nbghl("Directory")
nbghl("WarningMsg")
nbghl("Conceal")
nbghl("VertSplit")
nbghl("WinBar")
nbghl("WinBarNc")
nbghl("TabLineSel")
nbghl("BufferCurrent")
nbghl("BufferCurrentIndex")
nbghl("BufferCurrentMod")
nbghl("BufferCurrentSign")
nbghl("BufferCurrentTarget")
nbghl("BufferVisible")
nbghl("BufferVisibleIndex")
nbghl("BufferVisibleMod")
nbghl("BufferVisibleSign")
nbghl("BufferVisibleTarget")
nbghl("NormalFloat")
nbghl("CocFloating")
nbghl("Pmenu")
nbghl("CursorLine")
nbghl("ColorColumn")
